local cl = require("setup.ui.colors")

return {
	DiagnosticVirtualTextError = { bg = "none", fg = cl.red },
	DiagnosticVirtualTextWarn = { bg = "none", fg = cl.yellow },
	DiagnosticVirtualTextInfo = { bg = "none", fg = cl.green },
	DiagnosticVirtualTextHint = { bg = "none", fg = cl.blue },

	NeoTreeIndentMarker = { bg = "none", fg = cl.cyan },
	NeoTreeWinSeparator = { bg = "none", fg = cl.yellow },
	PmenuSel = { bg = cl.purple2, fg = cl.yellow4, bold = true },
	LineNr = { fg = cl.aqua, bold = true },
	CursorLineNr = { fg = cl.purple3, bold = true },
	-- FoldColumn = { bg = options.transparent and c.none or c.bg, fg = cl.cyan },
	TelescopeNormal = { link = "NormalFloat" },
	TelescopeResultsNormal = { bg = "none" },
	TelescopePromptTitle = { fg = cl.black, bg = cl.red2 },
	TelescopePreviewTitle = { fg = cl.black, bg = cl.cyan },
	TelescopeResultsTitle = { fg = cl.black, bg = cl.yellow2 },
	FloatBorder = { fg = cl.purple2, bg = "none" },
	WinSeparator = { fg = cl.purple2, bold = false },
	NeoTreeDirectoryIcon = { fg = cl.yellow3, bg = "none" },
	NavicText = { fg = cl.cyan, bg = "none" },
	NavicSeparator = { fg = cl.yellow2, bg = "none" },

	CmpItemKindConstant = { fg = cl.base09 },
	CmpItemKindFunction = { fg = cl.base0D },
	CmpItemKindIdentifier = { fg = cl.base08 },
	CmpItemKindField = { fg = cl.base08 },
	CmpItemKindVariable = { fg = cl.base0E },
	CmpItemKindSnippet = { fg = cl.red },
	CmpItemKindText = { fg = cl.base0B },
	CmpItemKindStructure = { fg = cl.base0E },
	CmpItemKindType = { fg = cl.base0A },
	CmpItemKindKeyword = { fg = cl.base07 },
	CmpItemKindMethod = { fg = cl.base0D },
	CmpItemKindConstructor = { fg = cl.blue },
	CmpItemKindFolder = { fg = cl.base07 },
	CmpItemKindModule = { fg = cl.base0A },
	CmpItemKindProperty = { fg = cl.base08 },
	CmpItemKindEnum = { fg = cl.blue },
	CmpItemKindUnit = { fg = cl.base0E },
	CmpItemKindClass = { fg = cl.teal },
	CmpItemKindFile = { fg = cl.base07 },
	CmpItemKindInterface = { fg = cl.green },
	CmpItemKindColor = { fg = cl.white },
	CmpItemKindReference = { fg = cl.base05 },
	CmpItemKindEnumMember = { fg = cl.purple },
	CmpItemKindStruct = { fg = cl.base0E },
	CmpItemKindValue = { fg = cl.cyan },
	CmpItemKindEvent = { fg = cl.yellow },
	CmpItemKindOperator = { fg = cl.base05 },
	CmpItemKindTypeParameter = { fg = cl.base08 },
	CmpItemKindCopilot = { fg = cl.green },

	GitSignsAdd = { fg = cl.green2 },
	GitSignsChange = { fg = cl.yellow2 },
	GitSignsDelete = { fg = cl.red2 },
}
